### ISSUE TITLE
add nets as a member

### ISSUE THREAD

**Issue by IsNoGood** [robotframework/foundation#8]
About Nets A/S

At Nets, we see easier products and solutions as the foundation for growth and progress – both in commerce and society. With 2,400 employees located in Denmark, Norway, Finland, Sweden and Estonia, we help financial institutions, businesses and merchants across the Nordic and Baltic regions make tomorrow a little easier for their customers while delivering unrivalled security and stability. Powering a tomorrow that’s easier than today. This is what drives us. Learn more on www.nets.eu
![nets_logo_pos_rgb](https://user-images.githubusercontent.com/1047173/47962222-2ccde100-e022-11e8-93b1-761a0d967b40.JPG)

**Comment by Tattoo** [comment]
Added in c36df5f416fb39593de5af0e96aee2a7f59cacc4
